---
general:
  buildTool: "mta"
  docker:
  name: "maven"
  image: "maven:3.5-jdk-8"
  pullImage : true

  
service:
  buildToolVersion: "MBTJ11N16" #see SAP Continuous Integration and Delivery service for more build tool version options
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: true
  Additional Unit Tests:
    npmExecuteScripts: false
  Acceptance:
    cloudFoundryDeploy: false
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "72af71a5trial_dev2-v74czq1b"
    cfSpace: "dev2"
    cfAppName: "cicd"
    cfCredentialsId: "cfdeploy"
    deployType: "standard"
    npmExecuteEndToEndTests: true
  Compliance:
    sonarExecuteScan: true 
    serverUrl: "https://sonarcloud.io"                                                   
    organization: "dev609"                                 
    projectKey: "dev609"                                  
    sonarTokenCredentialsId: "sonar"

  Release:
    cloudFoundryDeploy: true
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "72af71a5trial_dev2-v74czq1b"
    cfSpace: "dev2"
    cfAppName: "cicd"
    cfCredentialsId: "cfdeploy"
    deployType: "standard"
    tmsUpload: false
steps:
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
  npmExecuteLint:
    failOnError: true
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "qa1"
    credentialsId: "tms-sk"
